# Example Jira Integration Configuration
# Copy these settings to your .zen/config.yaml file

integrations:
  task_system: "jira"
  sync_enabled: true
  sync_frequency: "manual"
  
  # Provider-specific configurations
  providers:
    jira:
      # Your Jira instance URL (replace with your actual Jira URL)
      server_url: "https://your-company.atlassian.net"
      
      # Your Jira project key (replace with your actual project key)
      project_key: "PROJ"
      
      # Authentication type (basic, oauth2, or token)
      auth_type: "basic"
      
      # Reference to credentials in auth system
      credentials_ref: "jira_credentials"
      
      # Field mappings between Zen and Jira
      field_mapping:
        task_id: "key"
        title: "summary"
        description: "description"
        status: "status.name"
        priority: "priority.name"
        assignee: "assignee.displayName"
        created: "created"
        updated: "updated"
      
      # Sync direction
      sync_direction: "bidirectional"
      
      # Additional settings
      settings:
        issue_type: "Task"
        timeout_seconds: 30
