name: Documentation Generation

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pull-requests: write

env:
  GO_VERSION: '1.25'

jobs:
  generate-docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: make deps

    - name: Generate documentation
      run: make docs

    - name: Check for documentation changes
      id: check_changes
      run: |
        git add docs/
        if git diff --staged --quiet; then
          echo "No documentation changes to commit"
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "Documentation changes detected"
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request with documentation updates
      if: steps.check_changes.outputs.has_changes == 'true'
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "docs: update documentation for ${{ github.ref_name }}"
        title: "docs: update documentation for ${{ github.ref_name }}"
        body: |
          ## Documentation Update

          This PR contains automatically generated documentation updates for release ${{ github.ref_name }}.

          ### Changes
          - Updated CLI command documentation
          - Regenerated markdown files from code

          ### Generated by
          - Workflow: ${{ github.workflow }}
          - Run: ${{ github.run_id }}
          - Tag: ${{ github.ref_name }}

          This PR can be merged automatically as it only contains documentation updates.
        branch: docs/update-${{ github.ref_name }}
        delete-branch: true
        base: main
        add-paths: |
          docs/
